using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;

namespace InventorySystem
{
    /// <summary>
    /// Keeps the popup scripts of an <see cref="InventoryData"/>'s item groups up to date, as its Compile step's
    /// last part: with more than one group, one <c>{Group}Popup</c> per group is written to UniMVC's
    /// <c>Popups/Inventory</c> folder (a subclass of <c>InventoryGroupPopup</c> that only says which group it is);
    /// with a single group there are none, and the ones written before are deleted, as are those of removed or renamed
    /// groups. Only files this step wrote are ever deleted (they carry its marker), and a file whose content is
    /// already right isn't written again, so compiling without changes never triggers a script reload.
    /// </summary>
    internal static class InventoryGroupScripts
    {
        private const string MvcAssembly = "UniMVC.Runtime";
        private const string FallbackMvcRoot = "Assets/Scripts/MVC";
        private const string PopupFolder = "Popups/Inventory";
        private const string Marker = "Generated by InventoryData > Compile";

        /// <summary>
        /// Writes and removes the popup scripts for <paramref name="groups"/> (each group's member name and id).
        /// Returns whether any script was written or deleted - Unity then recompiles.
        /// </summary>
        public static bool Sync(List<KeyValuePair<string, int>> groups, out int written, out int deleted)
        {
            written = 0;
            deleted = 0;

            var wanted = new Dictionary<string, string>(StringComparer.Ordinal);
            if (groups.Count > 1)
            {
                foreach (var group in groups)
                {
                    wanted[group.Key + "Popup"] = group.Key;
                }
            }

            var assemblyPath = CompilationPipeline.GetAssemblyDefinitionFilePathFromAssemblyName(MvcAssembly);
            if (string.IsNullOrEmpty(assemblyPath))
            {
                if (wanted.Count > 0)
                {
                    Debug.LogWarning("[InventoryData] UniMVC isn't in the project, so the group popups weren't made.");
                }

                return false;
            }

            var folder = MvcRoot(assemblyPath) + "/" + PopupFolder;
            var fullFolder = ToFullPath(folder);

            foreach (var pair in wanted)
            {
                var path = folder + "/" + pair.Key + ".cs";
                var fullPath = ToFullPath(path);
                var source = Source(pair.Key, pair.Value);
                if (File.Exists(fullPath) && NormalizeNewlines(File.ReadAllText(fullPath)) == NormalizeNewlines(source))
                {
                    continue;
                }

                Directory.CreateDirectory(fullFolder);
                File.WriteAllText(fullPath, source);
                AssetDatabase.ImportAsset(path);
                written++;
            }

            if (Directory.Exists(fullFolder))
            {
                foreach (var file in Directory.GetFiles(fullFolder, "*Popup.cs"))
                {
                    var name = Path.GetFileNameWithoutExtension(file);
                    if (wanted.ContainsKey(name) || !File.ReadAllText(file).Contains(Marker))
                    {
                        continue;
                    }

                    if (AssetDatabase.DeleteAsset(folder + "/" + name + ".cs"))
                    {
                        deleted++;
                    }
                }
            }

            return written > 0 || deleted > 0;
        }

        private static string Source(string className, string groupName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("#if HAS_INVENTORY_SYSTEM && HAS_UNIMVC && HAS_EVENT_SYSTEM && HAS_INPUT_SYSTEM");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// " + Marker + ". Do not edit by hand: it is written again by every Compile, and deleted");
            sb.AppendLine("// when the group is removed or renamed, or the InventoryData is left with a single group.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("namespace InventorySystem.UI");
            sb.AppendLine("{");
            sb.AppendLine($"    /// <summary>The popup of the {groupName} group in an inventory window with several groups.</summary>");
            sb.AppendLine($"    public sealed class {className} : InventoryGroupPopup");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>The group this popup shows.</summary>");
            sb.AppendLine($"        public const ItemGroups GroupType = ItemGroups.{groupName};");
            sb.AppendLine();
            sb.AppendLine("        public override ItemGroups Group => GroupType;");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        // UniMVC's runtime asmdef sits in MVC/Bases/, so the MVC folder is its parent.
        private static string MvcRoot(string assemblyPath)
        {
            if (!assemblyPath.StartsWith("Assets/", StringComparison.Ordinal))
            {
                return FallbackMvcRoot;
            }

            var bases = Path.GetDirectoryName(assemblyPath)!;
            return Path.GetDirectoryName(bases)!.Replace('\\', '/');
        }

        private static string ToFullPath(string assetPath) =>
            Path.Combine(Directory.GetParent(Application.dataPath)!.FullName, assetPath.Replace('/', Path.DirectorySeparatorChar));

        private static string NormalizeNewlines(string text) => text.Replace("\r\n", "\n");
    }
}
